/*
Merchant APIs

Technical document APIs for Merchant APIs

API version: 6.0
Contact: duong.vu@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_merchant_apis

import (
	"encoding/json"
)

// checks if the ResponseReservedSchemaDataInnerRedemptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseReservedSchemaDataInnerRedemptions{}

// ResponseReservedSchemaDataInnerRedemptions Include information related to the use of the voucher (all types)
type ResponseReservedSchemaDataInnerRedemptions struct {
	// Contains redeemed SKU information of the voucher (for voucher type is conditional and support sku)
	RedeemSkuCodes []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner `json:"redeem_sku_codes,omitempty"`
	// Actual redemption value of voucher type = conditional
	RedemptionValue *int32 `json:"redemption_value,omitempty"`
}

// NewResponseReservedSchemaDataInnerRedemptions instantiates a new ResponseReservedSchemaDataInnerRedemptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseReservedSchemaDataInnerRedemptions() *ResponseReservedSchemaDataInnerRedemptions {
	this := ResponseReservedSchemaDataInnerRedemptions{}
	return &this
}

// NewResponseReservedSchemaDataInnerRedemptionsWithDefaults instantiates a new ResponseReservedSchemaDataInnerRedemptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseReservedSchemaDataInnerRedemptionsWithDefaults() *ResponseReservedSchemaDataInnerRedemptions {
	this := ResponseReservedSchemaDataInnerRedemptions{}
	return &this
}

// GetRedeemSkuCodes returns the RedeemSkuCodes field value if set, zero value otherwise.
func (o *ResponseReservedSchemaDataInnerRedemptions) GetRedeemSkuCodes() []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner {
	if o == nil || IsNil(o.RedeemSkuCodes) {
		var ret []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
		return ret
	}
	return o.RedeemSkuCodes
}

// GetRedeemSkuCodesOk returns a tuple with the RedeemSkuCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseReservedSchemaDataInnerRedemptions) GetRedeemSkuCodesOk() ([]ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner, bool) {
	if o == nil || IsNil(o.RedeemSkuCodes) {
		return nil, false
	}
	return o.RedeemSkuCodes, true
}

// HasRedeemSkuCodes returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInnerRedemptions) HasRedeemSkuCodes() bool {
	if o != nil && !IsNil(o.RedeemSkuCodes) {
		return true
	}

	return false
}

// SetRedeemSkuCodes gets a reference to the given []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner and assigns it to the RedeemSkuCodes field.
func (o *ResponseReservedSchemaDataInnerRedemptions) SetRedeemSkuCodes(v []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner) {
	o.RedeemSkuCodes = v
}

// GetRedemptionValue returns the RedemptionValue field value if set, zero value otherwise.
func (o *ResponseReservedSchemaDataInnerRedemptions) GetRedemptionValue() int32 {
	if o == nil || IsNil(o.RedemptionValue) {
		var ret int32
		return ret
	}
	return *o.RedemptionValue
}

// GetRedemptionValueOk returns a tuple with the RedemptionValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseReservedSchemaDataInnerRedemptions) GetRedemptionValueOk() (*int32, bool) {
	if o == nil || IsNil(o.RedemptionValue) {
		return nil, false
	}
	return o.RedemptionValue, true
}

// HasRedemptionValue returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInnerRedemptions) HasRedemptionValue() bool {
	if o != nil && !IsNil(o.RedemptionValue) {
		return true
	}

	return false
}

// SetRedemptionValue gets a reference to the given int32 and assigns it to the RedemptionValue field.
func (o *ResponseReservedSchemaDataInnerRedemptions) SetRedemptionValue(v int32) {
	o.RedemptionValue = &v
}

func (o ResponseReservedSchemaDataInnerRedemptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseReservedSchemaDataInnerRedemptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RedeemSkuCodes) {
		toSerialize["redeem_sku_codes"] = o.RedeemSkuCodes
	}
	if !IsNil(o.RedemptionValue) {
		toSerialize["redemption_value"] = o.RedemptionValue
	}
	return toSerialize, nil
}

type NullableResponseReservedSchemaDataInnerRedemptions struct {
	value *ResponseReservedSchemaDataInnerRedemptions
	isSet bool
}

func (v NullableResponseReservedSchemaDataInnerRedemptions) Get() *ResponseReservedSchemaDataInnerRedemptions {
	return v.value
}

func (v *NullableResponseReservedSchemaDataInnerRedemptions) Set(val *ResponseReservedSchemaDataInnerRedemptions) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseReservedSchemaDataInnerRedemptions) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseReservedSchemaDataInnerRedemptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseReservedSchemaDataInnerRedemptions(val *ResponseReservedSchemaDataInnerRedemptions) *NullableResponseReservedSchemaDataInnerRedemptions {
	return &NullableResponseReservedSchemaDataInnerRedemptions{value: val, isSet: true}
}

func (v NullableResponseReservedSchemaDataInnerRedemptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseReservedSchemaDataInnerRedemptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


