/*
Merchant APIs

Technical document APIs for Merchant APIs

API version: 6.0
Contact: duong.vu@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_merchant_api

import (
	"encoding/json"
)

// checks if the ResponseCheckMultipleSchemaDataInnerRedemptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCheckMultipleSchemaDataInnerRedemptions{}

// ResponseCheckMultipleSchemaDataInnerRedemptions Include information related to the use of the voucher (all types)
type ResponseCheckMultipleSchemaDataInnerRedemptions struct {
	// Contains redeemed SKU information of the voucher (for voucher type is conditional and support sku)
	RedeemSkuCodes []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner `json:"redeem_sku_codes,omitempty"`
	// Actual redemption value of voucher type = conditional
	RedemptionValue *int64 `json:"redemption_value,omitempty"`
	UsedStore *ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore `json:"used_store,omitempty"`
	// Date voucher marked as used in case the voucher has been redeemed. Format (YYYY-MM-DD HH:MM:SS)
	UsedDate *string `json:"used_date,omitempty"`
	// Bill number for which voucher used/reserved
	BillNumber *string `json:"bill_number,omitempty"`
}

// NewResponseCheckMultipleSchemaDataInnerRedemptions instantiates a new ResponseCheckMultipleSchemaDataInnerRedemptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCheckMultipleSchemaDataInnerRedemptions() *ResponseCheckMultipleSchemaDataInnerRedemptions {
	this := ResponseCheckMultipleSchemaDataInnerRedemptions{}
	return &this
}

// NewResponseCheckMultipleSchemaDataInnerRedemptionsWithDefaults instantiates a new ResponseCheckMultipleSchemaDataInnerRedemptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCheckMultipleSchemaDataInnerRedemptionsWithDefaults() *ResponseCheckMultipleSchemaDataInnerRedemptions {
	this := ResponseCheckMultipleSchemaDataInnerRedemptions{}
	return &this
}

// GetRedeemSkuCodes returns the RedeemSkuCodes field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetRedeemSkuCodes() []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner {
	if o == nil || IsNil(o.RedeemSkuCodes) {
		var ret []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
		return ret
	}
	return o.RedeemSkuCodes
}

// GetRedeemSkuCodesOk returns a tuple with the RedeemSkuCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetRedeemSkuCodesOk() ([]ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner, bool) {
	if o == nil || IsNil(o.RedeemSkuCodes) {
		return nil, false
	}
	return o.RedeemSkuCodes, true
}

// HasRedeemSkuCodes returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) HasRedeemSkuCodes() bool {
	if o != nil && !IsNil(o.RedeemSkuCodes) {
		return true
	}

	return false
}

// SetRedeemSkuCodes gets a reference to the given []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner and assigns it to the RedeemSkuCodes field.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) SetRedeemSkuCodes(v []ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner) {
	o.RedeemSkuCodes = v
}

// GetRedemptionValue returns the RedemptionValue field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetRedemptionValue() int64 {
	if o == nil || IsNil(o.RedemptionValue) {
		var ret int64
		return ret
	}
	return *o.RedemptionValue
}

// GetRedemptionValueOk returns a tuple with the RedemptionValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetRedemptionValueOk() (*int64, bool) {
	if o == nil || IsNil(o.RedemptionValue) {
		return nil, false
	}
	return o.RedemptionValue, true
}

// HasRedemptionValue returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) HasRedemptionValue() bool {
	if o != nil && !IsNil(o.RedemptionValue) {
		return true
	}

	return false
}

// SetRedemptionValue gets a reference to the given int64 and assigns it to the RedemptionValue field.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) SetRedemptionValue(v int64) {
	o.RedemptionValue = &v
}

// GetUsedStore returns the UsedStore field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetUsedStore() ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore {
	if o == nil || IsNil(o.UsedStore) {
		var ret ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore
		return ret
	}
	return *o.UsedStore
}

// GetUsedStoreOk returns a tuple with the UsedStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetUsedStoreOk() (*ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore, bool) {
	if o == nil || IsNil(o.UsedStore) {
		return nil, false
	}
	return o.UsedStore, true
}

// HasUsedStore returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) HasUsedStore() bool {
	if o != nil && !IsNil(o.UsedStore) {
		return true
	}

	return false
}

// SetUsedStore gets a reference to the given ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore and assigns it to the UsedStore field.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) SetUsedStore(v ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore) {
	o.UsedStore = &v
}

// GetUsedDate returns the UsedDate field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetUsedDate() string {
	if o == nil || IsNil(o.UsedDate) {
		var ret string
		return ret
	}
	return *o.UsedDate
}

// GetUsedDateOk returns a tuple with the UsedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetUsedDateOk() (*string, bool) {
	if o == nil || IsNil(o.UsedDate) {
		return nil, false
	}
	return o.UsedDate, true
}

// HasUsedDate returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) HasUsedDate() bool {
	if o != nil && !IsNil(o.UsedDate) {
		return true
	}

	return false
}

// SetUsedDate gets a reference to the given string and assigns it to the UsedDate field.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) SetUsedDate(v string) {
	o.UsedDate = &v
}

// GetBillNumber returns the BillNumber field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetBillNumber() string {
	if o == nil || IsNil(o.BillNumber) {
		var ret string
		return ret
	}
	return *o.BillNumber
}

// GetBillNumberOk returns a tuple with the BillNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) GetBillNumberOk() (*string, bool) {
	if o == nil || IsNil(o.BillNumber) {
		return nil, false
	}
	return o.BillNumber, true
}

// HasBillNumber returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) HasBillNumber() bool {
	if o != nil && !IsNil(o.BillNumber) {
		return true
	}

	return false
}

// SetBillNumber gets a reference to the given string and assigns it to the BillNumber field.
func (o *ResponseCheckMultipleSchemaDataInnerRedemptions) SetBillNumber(v string) {
	o.BillNumber = &v
}

func (o ResponseCheckMultipleSchemaDataInnerRedemptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCheckMultipleSchemaDataInnerRedemptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RedeemSkuCodes) {
		toSerialize["redeem_sku_codes"] = o.RedeemSkuCodes
	}
	if !IsNil(o.RedemptionValue) {
		toSerialize["redemption_value"] = o.RedemptionValue
	}
	if !IsNil(o.UsedStore) {
		toSerialize["used_store"] = o.UsedStore
	}
	if !IsNil(o.UsedDate) {
		toSerialize["used_date"] = o.UsedDate
	}
	if !IsNil(o.BillNumber) {
		toSerialize["bill_number"] = o.BillNumber
	}
	return toSerialize, nil
}

type NullableResponseCheckMultipleSchemaDataInnerRedemptions struct {
	value *ResponseCheckMultipleSchemaDataInnerRedemptions
	isSet bool
}

func (v NullableResponseCheckMultipleSchemaDataInnerRedemptions) Get() *ResponseCheckMultipleSchemaDataInnerRedemptions {
	return v.value
}

func (v *NullableResponseCheckMultipleSchemaDataInnerRedemptions) Set(val *ResponseCheckMultipleSchemaDataInnerRedemptions) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCheckMultipleSchemaDataInnerRedemptions) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCheckMultipleSchemaDataInnerRedemptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCheckMultipleSchemaDataInnerRedemptions(val *ResponseCheckMultipleSchemaDataInnerRedemptions) *NullableResponseCheckMultipleSchemaDataInnerRedemptions {
	return &NullableResponseCheckMultipleSchemaDataInnerRedemptions{value: val, isSet: true}
}

func (v NullableResponseCheckMultipleSchemaDataInnerRedemptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCheckMultipleSchemaDataInnerRedemptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


