/*
Merchant APIs

Technical document APIs for Merchant APIs

API version: 6.0
Contact: duong.vu@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_merchant_apis

import (
	"encoding/json"
)

// checks if the ResponseUnReservedSchemaDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseUnReservedSchemaDataInner{}

// ResponseUnReservedSchemaDataInner struct for ResponseUnReservedSchemaDataInner
type ResponseUnReservedSchemaDataInner struct {
	// Voucher code
	Code *string `json:"code,omitempty"`
	// Value of voucher
	Value NullableInt32 `json:"value,omitempty"`
	// Voucher type, standard or conditional
	VoucherType *string `json:"voucher_type,omitempty"`
}

// NewResponseUnReservedSchemaDataInner instantiates a new ResponseUnReservedSchemaDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseUnReservedSchemaDataInner() *ResponseUnReservedSchemaDataInner {
	this := ResponseUnReservedSchemaDataInner{}
	return &this
}

// NewResponseUnReservedSchemaDataInnerWithDefaults instantiates a new ResponseUnReservedSchemaDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseUnReservedSchemaDataInnerWithDefaults() *ResponseUnReservedSchemaDataInner {
	this := ResponseUnReservedSchemaDataInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ResponseUnReservedSchemaDataInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUnReservedSchemaDataInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ResponseUnReservedSchemaDataInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ResponseUnReservedSchemaDataInner) SetCode(v string) {
	o.Code = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseUnReservedSchemaDataInner) GetValue() int32 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret int32
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseUnReservedSchemaDataInner) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *ResponseUnReservedSchemaDataInner) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableInt32 and assigns it to the Value field.
func (o *ResponseUnReservedSchemaDataInner) SetValue(v int32) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *ResponseUnReservedSchemaDataInner) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *ResponseUnReservedSchemaDataInner) UnsetValue() {
	o.Value.Unset()
}

// GetVoucherType returns the VoucherType field value if set, zero value otherwise.
func (o *ResponseUnReservedSchemaDataInner) GetVoucherType() string {
	if o == nil || IsNil(o.VoucherType) {
		var ret string
		return ret
	}
	return *o.VoucherType
}

// GetVoucherTypeOk returns a tuple with the VoucherType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUnReservedSchemaDataInner) GetVoucherTypeOk() (*string, bool) {
	if o == nil || IsNil(o.VoucherType) {
		return nil, false
	}
	return o.VoucherType, true
}

// HasVoucherType returns a boolean if a field has been set.
func (o *ResponseUnReservedSchemaDataInner) HasVoucherType() bool {
	if o != nil && !IsNil(o.VoucherType) {
		return true
	}

	return false
}

// SetVoucherType gets a reference to the given string and assigns it to the VoucherType field.
func (o *ResponseUnReservedSchemaDataInner) SetVoucherType(v string) {
	o.VoucherType = &v
}

func (o ResponseUnReservedSchemaDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseUnReservedSchemaDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if !IsNil(o.VoucherType) {
		toSerialize["voucher_type"] = o.VoucherType
	}
	return toSerialize, nil
}

type NullableResponseUnReservedSchemaDataInner struct {
	value *ResponseUnReservedSchemaDataInner
	isSet bool
}

func (v NullableResponseUnReservedSchemaDataInner) Get() *ResponseUnReservedSchemaDataInner {
	return v.value
}

func (v *NullableResponseUnReservedSchemaDataInner) Set(val *ResponseUnReservedSchemaDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseUnReservedSchemaDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseUnReservedSchemaDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseUnReservedSchemaDataInner(val *ResponseUnReservedSchemaDataInner) *NullableResponseUnReservedSchemaDataInner {
	return &NullableResponseUnReservedSchemaDataInner{value: val, isSet: true}
}

func (v NullableResponseUnReservedSchemaDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseUnReservedSchemaDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


