/*
Merchant APIs

Technical document APIs for Merchant APIs

API version: 6.0
Contact: duong.vu@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit-merchant-apis

import (
	"encoding/json"
)

// checks if the ResponseCheckMultipleSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCheckMultipleSchema{}

// ResponseCheckMultipleSchema struct for ResponseCheckMultipleSchema
type ResponseCheckMultipleSchema struct {
	Success *bool `json:"success,omitempty"`
	// Result code if failed. In case of successful request: value is null
	ReturnCode NullableString `json:"return_code,omitempty"`
	// Message notification in English
	MessageEn *string `json:"message_en,omitempty"`
	// Message notification in Vietnamese
	MessageVi *string `json:"message_vi,omitempty"`
	// Detail items of voucher, if result is failed, response will return the first voucher code which is invalid
	Data []ResponseCheckMultipleSchemaDataInner `json:"data,omitempty"`
}

// NewResponseCheckMultipleSchema instantiates a new ResponseCheckMultipleSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCheckMultipleSchema() *ResponseCheckMultipleSchema {
	this := ResponseCheckMultipleSchema{}
	return &this
}

// NewResponseCheckMultipleSchemaWithDefaults instantiates a new ResponseCheckMultipleSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCheckMultipleSchemaWithDefaults() *ResponseCheckMultipleSchema {
	this := ResponseCheckMultipleSchema{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchema) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchema) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchema) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ResponseCheckMultipleSchema) SetSuccess(v bool) {
	o.Success = &v
}

// GetReturnCode returns the ReturnCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseCheckMultipleSchema) GetReturnCode() string {
	if o == nil || IsNil(o.ReturnCode.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnCode.Get()
}

// GetReturnCodeOk returns a tuple with the ReturnCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseCheckMultipleSchema) GetReturnCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnCode.Get(), o.ReturnCode.IsSet()
}

// HasReturnCode returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchema) HasReturnCode() bool {
	if o != nil && o.ReturnCode.IsSet() {
		return true
	}

	return false
}

// SetReturnCode gets a reference to the given NullableString and assigns it to the ReturnCode field.
func (o *ResponseCheckMultipleSchema) SetReturnCode(v string) {
	o.ReturnCode.Set(&v)
}
// SetReturnCodeNil sets the value for ReturnCode to be an explicit nil
func (o *ResponseCheckMultipleSchema) SetReturnCodeNil() {
	o.ReturnCode.Set(nil)
}

// UnsetReturnCode ensures that no value is present for ReturnCode, not even an explicit nil
func (o *ResponseCheckMultipleSchema) UnsetReturnCode() {
	o.ReturnCode.Unset()
}

// GetMessageEn returns the MessageEn field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchema) GetMessageEn() string {
	if o == nil || IsNil(o.MessageEn) {
		var ret string
		return ret
	}
	return *o.MessageEn
}

// GetMessageEnOk returns a tuple with the MessageEn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchema) GetMessageEnOk() (*string, bool) {
	if o == nil || IsNil(o.MessageEn) {
		return nil, false
	}
	return o.MessageEn, true
}

// HasMessageEn returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchema) HasMessageEn() bool {
	if o != nil && !IsNil(o.MessageEn) {
		return true
	}

	return false
}

// SetMessageEn gets a reference to the given string and assigns it to the MessageEn field.
func (o *ResponseCheckMultipleSchema) SetMessageEn(v string) {
	o.MessageEn = &v
}

// GetMessageVi returns the MessageVi field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchema) GetMessageVi() string {
	if o == nil || IsNil(o.MessageVi) {
		var ret string
		return ret
	}
	return *o.MessageVi
}

// GetMessageViOk returns a tuple with the MessageVi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchema) GetMessageViOk() (*string, bool) {
	if o == nil || IsNil(o.MessageVi) {
		return nil, false
	}
	return o.MessageVi, true
}

// HasMessageVi returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchema) HasMessageVi() bool {
	if o != nil && !IsNil(o.MessageVi) {
		return true
	}

	return false
}

// SetMessageVi gets a reference to the given string and assigns it to the MessageVi field.
func (o *ResponseCheckMultipleSchema) SetMessageVi(v string) {
	o.MessageVi = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseCheckMultipleSchema) GetData() []ResponseCheckMultipleSchemaDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []ResponseCheckMultipleSchemaDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCheckMultipleSchema) GetDataOk() ([]ResponseCheckMultipleSchemaDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseCheckMultipleSchema) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ResponseCheckMultipleSchemaDataInner and assigns it to the Data field.
func (o *ResponseCheckMultipleSchema) SetData(v []ResponseCheckMultipleSchemaDataInner) {
	o.Data = v
}

func (o ResponseCheckMultipleSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCheckMultipleSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if o.ReturnCode.IsSet() {
		toSerialize["return_code"] = o.ReturnCode.Get()
	}
	if !IsNil(o.MessageEn) {
		toSerialize["message_en"] = o.MessageEn
	}
	if !IsNil(o.MessageVi) {
		toSerialize["message_vi"] = o.MessageVi
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableResponseCheckMultipleSchema struct {
	value *ResponseCheckMultipleSchema
	isSet bool
}

func (v NullableResponseCheckMultipleSchema) Get() *ResponseCheckMultipleSchema {
	return v.value
}

func (v *NullableResponseCheckMultipleSchema) Set(val *ResponseCheckMultipleSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCheckMultipleSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCheckMultipleSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCheckMultipleSchema(val *ResponseCheckMultipleSchema) *NullableResponseCheckMultipleSchema {
	return &NullableResponseCheckMultipleSchema{value: val, isSet: true}
}

func (v NullableResponseCheckMultipleSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCheckMultipleSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


