/*
Merchant APIs

Technical document APIs for Merchant APIs

API version: 6.0
Contact: duong.vu@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_merchant_apis

import (
	"encoding/json"
)

// checks if the ResponseMarkUseMultipleSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseMarkUseMultipleSchema{}

// ResponseMarkUseMultipleSchema struct for ResponseMarkUseMultipleSchema
type ResponseMarkUseMultipleSchema struct {
	Success *bool `json:"success,omitempty"`
	// Result code if failed. In case of successful request: value is null
	ReturnCode NullableString `json:"return_code,omitempty"`
	// Message notification in English
	MessageEn *string `json:"message_en,omitempty"`
	// Message notification in Vietnamese
	MessageVi *string `json:"message_vi,omitempty"`
	// Detail items of voucher, if result is failed, response will return the first voucher code which is invalid
	Data []ResponseMarkUseMultipleSchemaDataInner `json:"data,omitempty"`
	// Transaction ID (if mark used successfully)
	TransactionId *string `json:"transaction_id,omitempty"`
	// Bill number that vouchers were marked as used for.
	BillNumber *string `json:"bill_number,omitempty"`
}

// NewResponseMarkUseMultipleSchema instantiates a new ResponseMarkUseMultipleSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseMarkUseMultipleSchema() *ResponseMarkUseMultipleSchema {
	this := ResponseMarkUseMultipleSchema{}
	return &this
}

// NewResponseMarkUseMultipleSchemaWithDefaults instantiates a new ResponseMarkUseMultipleSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseMarkUseMultipleSchemaWithDefaults() *ResponseMarkUseMultipleSchema {
	this := ResponseMarkUseMultipleSchema{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ResponseMarkUseMultipleSchema) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMarkUseMultipleSchema) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ResponseMarkUseMultipleSchema) SetSuccess(v bool) {
	o.Success = &v
}

// GetReturnCode returns the ReturnCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseMarkUseMultipleSchema) GetReturnCode() string {
	if o == nil || IsNil(o.ReturnCode.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnCode.Get()
}

// GetReturnCodeOk returns a tuple with the ReturnCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseMarkUseMultipleSchema) GetReturnCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnCode.Get(), o.ReturnCode.IsSet()
}

// HasReturnCode returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasReturnCode() bool {
	if o != nil && o.ReturnCode.IsSet() {
		return true
	}

	return false
}

// SetReturnCode gets a reference to the given NullableString and assigns it to the ReturnCode field.
func (o *ResponseMarkUseMultipleSchema) SetReturnCode(v string) {
	o.ReturnCode.Set(&v)
}
// SetReturnCodeNil sets the value for ReturnCode to be an explicit nil
func (o *ResponseMarkUseMultipleSchema) SetReturnCodeNil() {
	o.ReturnCode.Set(nil)
}

// UnsetReturnCode ensures that no value is present for ReturnCode, not even an explicit nil
func (o *ResponseMarkUseMultipleSchema) UnsetReturnCode() {
	o.ReturnCode.Unset()
}

// GetMessageEn returns the MessageEn field value if set, zero value otherwise.
func (o *ResponseMarkUseMultipleSchema) GetMessageEn() string {
	if o == nil || IsNil(o.MessageEn) {
		var ret string
		return ret
	}
	return *o.MessageEn
}

// GetMessageEnOk returns a tuple with the MessageEn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMarkUseMultipleSchema) GetMessageEnOk() (*string, bool) {
	if o == nil || IsNil(o.MessageEn) {
		return nil, false
	}
	return o.MessageEn, true
}

// HasMessageEn returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasMessageEn() bool {
	if o != nil && !IsNil(o.MessageEn) {
		return true
	}

	return false
}

// SetMessageEn gets a reference to the given string and assigns it to the MessageEn field.
func (o *ResponseMarkUseMultipleSchema) SetMessageEn(v string) {
	o.MessageEn = &v
}

// GetMessageVi returns the MessageVi field value if set, zero value otherwise.
func (o *ResponseMarkUseMultipleSchema) GetMessageVi() string {
	if o == nil || IsNil(o.MessageVi) {
		var ret string
		return ret
	}
	return *o.MessageVi
}

// GetMessageViOk returns a tuple with the MessageVi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMarkUseMultipleSchema) GetMessageViOk() (*string, bool) {
	if o == nil || IsNil(o.MessageVi) {
		return nil, false
	}
	return o.MessageVi, true
}

// HasMessageVi returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasMessageVi() bool {
	if o != nil && !IsNil(o.MessageVi) {
		return true
	}

	return false
}

// SetMessageVi gets a reference to the given string and assigns it to the MessageVi field.
func (o *ResponseMarkUseMultipleSchema) SetMessageVi(v string) {
	o.MessageVi = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseMarkUseMultipleSchema) GetData() []ResponseMarkUseMultipleSchemaDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []ResponseMarkUseMultipleSchemaDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMarkUseMultipleSchema) GetDataOk() ([]ResponseMarkUseMultipleSchemaDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ResponseMarkUseMultipleSchemaDataInner and assigns it to the Data field.
func (o *ResponseMarkUseMultipleSchema) SetData(v []ResponseMarkUseMultipleSchemaDataInner) {
	o.Data = v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *ResponseMarkUseMultipleSchema) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMarkUseMultipleSchema) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *ResponseMarkUseMultipleSchema) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetBillNumber returns the BillNumber field value if set, zero value otherwise.
func (o *ResponseMarkUseMultipleSchema) GetBillNumber() string {
	if o == nil || IsNil(o.BillNumber) {
		var ret string
		return ret
	}
	return *o.BillNumber
}

// GetBillNumberOk returns a tuple with the BillNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMarkUseMultipleSchema) GetBillNumberOk() (*string, bool) {
	if o == nil || IsNil(o.BillNumber) {
		return nil, false
	}
	return o.BillNumber, true
}

// HasBillNumber returns a boolean if a field has been set.
func (o *ResponseMarkUseMultipleSchema) HasBillNumber() bool {
	if o != nil && !IsNil(o.BillNumber) {
		return true
	}

	return false
}

// SetBillNumber gets a reference to the given string and assigns it to the BillNumber field.
func (o *ResponseMarkUseMultipleSchema) SetBillNumber(v string) {
	o.BillNumber = &v
}

func (o ResponseMarkUseMultipleSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseMarkUseMultipleSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if o.ReturnCode.IsSet() {
		toSerialize["return_code"] = o.ReturnCode.Get()
	}
	if !IsNil(o.MessageEn) {
		toSerialize["message_en"] = o.MessageEn
	}
	if !IsNil(o.MessageVi) {
		toSerialize["message_vi"] = o.MessageVi
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.BillNumber) {
		toSerialize["bill_number"] = o.BillNumber
	}
	return toSerialize, nil
}

type NullableResponseMarkUseMultipleSchema struct {
	value *ResponseMarkUseMultipleSchema
	isSet bool
}

func (v NullableResponseMarkUseMultipleSchema) Get() *ResponseMarkUseMultipleSchema {
	return v.value
}

func (v *NullableResponseMarkUseMultipleSchema) Set(val *ResponseMarkUseMultipleSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseMarkUseMultipleSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseMarkUseMultipleSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseMarkUseMultipleSchema(val *ResponseMarkUseMultipleSchema) *NullableResponseMarkUseMultipleSchema {
	return &NullableResponseMarkUseMultipleSchema{value: val, isSet: true}
}

func (v NullableResponseMarkUseMultipleSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseMarkUseMultipleSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


