/*
Merchant APIs

Technical document APIs for Merchant APIs

API version: 6.0
Contact: duong.vu@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit-merchant-apis

import (
	"encoding/json"
)

// checks if the ResponseReservedSchemaDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseReservedSchemaDataInner{}

// ResponseReservedSchemaDataInner struct for ResponseReservedSchemaDataInner
type ResponseReservedSchemaDataInner struct {
	// Voucher code
	Code *string `json:"code,omitempty"`
	// Value of voucher
	Value NullableInt32 `json:"value,omitempty"`
	// Voucher type, standard or conditional
	VoucherType *string `json:"voucher_type,omitempty"`
	Conditions *ResponseMarkUseMultipleSchemaDataInnerConditions `json:"conditions,omitempty"`
	Redemptions *ResponseReservedSchemaDataInnerRedemptions `json:"redemptions,omitempty"`
}

// NewResponseReservedSchemaDataInner instantiates a new ResponseReservedSchemaDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseReservedSchemaDataInner() *ResponseReservedSchemaDataInner {
	this := ResponseReservedSchemaDataInner{}
	return &this
}

// NewResponseReservedSchemaDataInnerWithDefaults instantiates a new ResponseReservedSchemaDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseReservedSchemaDataInnerWithDefaults() *ResponseReservedSchemaDataInner {
	this := ResponseReservedSchemaDataInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ResponseReservedSchemaDataInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseReservedSchemaDataInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ResponseReservedSchemaDataInner) SetCode(v string) {
	o.Code = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseReservedSchemaDataInner) GetValue() int32 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret int32
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseReservedSchemaDataInner) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInner) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableInt32 and assigns it to the Value field.
func (o *ResponseReservedSchemaDataInner) SetValue(v int32) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *ResponseReservedSchemaDataInner) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *ResponseReservedSchemaDataInner) UnsetValue() {
	o.Value.Unset()
}

// GetVoucherType returns the VoucherType field value if set, zero value otherwise.
func (o *ResponseReservedSchemaDataInner) GetVoucherType() string {
	if o == nil || IsNil(o.VoucherType) {
		var ret string
		return ret
	}
	return *o.VoucherType
}

// GetVoucherTypeOk returns a tuple with the VoucherType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseReservedSchemaDataInner) GetVoucherTypeOk() (*string, bool) {
	if o == nil || IsNil(o.VoucherType) {
		return nil, false
	}
	return o.VoucherType, true
}

// HasVoucherType returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInner) HasVoucherType() bool {
	if o != nil && !IsNil(o.VoucherType) {
		return true
	}

	return false
}

// SetVoucherType gets a reference to the given string and assigns it to the VoucherType field.
func (o *ResponseReservedSchemaDataInner) SetVoucherType(v string) {
	o.VoucherType = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ResponseReservedSchemaDataInner) GetConditions() ResponseMarkUseMultipleSchemaDataInnerConditions {
	if o == nil || IsNil(o.Conditions) {
		var ret ResponseMarkUseMultipleSchemaDataInnerConditions
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseReservedSchemaDataInner) GetConditionsOk() (*ResponseMarkUseMultipleSchemaDataInnerConditions, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInner) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given ResponseMarkUseMultipleSchemaDataInnerConditions and assigns it to the Conditions field.
func (o *ResponseReservedSchemaDataInner) SetConditions(v ResponseMarkUseMultipleSchemaDataInnerConditions) {
	o.Conditions = &v
}

// GetRedemptions returns the Redemptions field value if set, zero value otherwise.
func (o *ResponseReservedSchemaDataInner) GetRedemptions() ResponseReservedSchemaDataInnerRedemptions {
	if o == nil || IsNil(o.Redemptions) {
		var ret ResponseReservedSchemaDataInnerRedemptions
		return ret
	}
	return *o.Redemptions
}

// GetRedemptionsOk returns a tuple with the Redemptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseReservedSchemaDataInner) GetRedemptionsOk() (*ResponseReservedSchemaDataInnerRedemptions, bool) {
	if o == nil || IsNil(o.Redemptions) {
		return nil, false
	}
	return o.Redemptions, true
}

// HasRedemptions returns a boolean if a field has been set.
func (o *ResponseReservedSchemaDataInner) HasRedemptions() bool {
	if o != nil && !IsNil(o.Redemptions) {
		return true
	}

	return false
}

// SetRedemptions gets a reference to the given ResponseReservedSchemaDataInnerRedemptions and assigns it to the Redemptions field.
func (o *ResponseReservedSchemaDataInner) SetRedemptions(v ResponseReservedSchemaDataInnerRedemptions) {
	o.Redemptions = &v
}

func (o ResponseReservedSchemaDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseReservedSchemaDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if !IsNil(o.VoucherType) {
		toSerialize["voucher_type"] = o.VoucherType
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Redemptions) {
		toSerialize["redemptions"] = o.Redemptions
	}
	return toSerialize, nil
}

type NullableResponseReservedSchemaDataInner struct {
	value *ResponseReservedSchemaDataInner
	isSet bool
}

func (v NullableResponseReservedSchemaDataInner) Get() *ResponseReservedSchemaDataInner {
	return v.value
}

func (v *NullableResponseReservedSchemaDataInner) Set(val *ResponseReservedSchemaDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseReservedSchemaDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseReservedSchemaDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseReservedSchemaDataInner(val *ResponseReservedSchemaDataInner) *NullableResponseReservedSchemaDataInner {
	return &NullableResponseReservedSchemaDataInner{value: val, isSet: true}
}

func (v NullableResponseReservedSchemaDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseReservedSchemaDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


